services:
  backend:
    build: .
    container_name: backend_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:tharun%402004@db:5432/chat_db
      - SECRET_KEY=punkrocker
      - ALGORITHM=HS256
    volumes:
      - ./new_chat_app_backend:/new_chat_app_backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tharun@2004
      - POSTGRES_DB=chat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  chat:
    driver: bridge